In [215]:
from heapq import heappush, heappop
from collections import defaultdict 
from math import inf
import numpy as np 

In [216]:
def init_state() : 
    x = np.arange(9) 
    np.random.shuffle(x)
    return x.reshape(3,3)

In [217]:
def manhattan_distance(x,y) : 
    return abs(x[0] - y[0]) + abs(x[1] - y[1])

In [218]:
goal_state = np.array( [ 
                        [0, 1, 2],
                        [3, 4, 5], 
                        [6, 7, 8],
                ])

def estimated_cost(a) : 
    sum_ = 0 
    for i in range(8) : 
        x, y = np.where(a == i) 
        x_, y_ = np.where(goal_state == i)
        sum_ += manhattan_distance((x,y) , (x_,y_))
    return sum_

In [219]:
def adjacents(x, y) : 
    for m, n in {(0, 1), (0, -1), (1, 0), (-1, 0)} : 
        x_, y_ = x + m , y + n 
        if 0 <= x_ <= 2 and 0 <= y_ <= 2 : 
            yield x_, y_
            
def next_states(s) : 
    x, y = np.where(s == 0) 
    x, y = x[0], y[0] 
    for x_, y_ in adjacents(x,y) : 
        next_s = np.copy(s)
        next_s[x][y] = next_s[x_][y_] 
        next_s[x_][y_] = 0 
        yield next_s
    return 

In [220]:
def is_goal_state(x) : 
    return np.all(x == goal_state)
def hash_(x) : 
    return str(x.reshape(-1))[1:-1]
def array_from_hash(x) : 
    return np.fromstring(x, dtype=int, sep=' ').reshape(3,3)
def search(s) : 
    heap = [(0, hash_(s))] 
    g = defaultdict(lambda : float('inf'))
    g[hash_(s)] = 0 
    visited = set()
    while heap : 
        _, v = heappop(heap) 
        v = array_from_hash(v)
        if is_goal_state(v): 
            return v
        for next_ in next_states(v) : 
            if hash_(next_) not in visited and \
                g[hash_(v)] + 1 < g[hash_(next_)] :   
                g[hash_(next_)] = g[hash_(v)] + 1 
                heappush(heap, (g[hash_(next_)] + \
                                estimated_cost(next_),\
                                hash_array(next_)))
            
        visited |= {hash_(v)}

In [221]:
x = init_state()
x

array([[0, 5, 1],
       [6, 8, 4],
       [3, 2, 7]])

In [222]:
search(x)

[[0 5 1]
 [6 8 4]
 [3 2 7]] 

[[5 0 1]
 [6 8 4]
 [3 2 7]] 

[[6 5 1]
 [0 8 4]
 [3 2 7]] 

[[5 1 0]
 [6 8 4]
 [3 2 7]] 

[[6 5 1]
 [3 8 4]
 [0 2 7]] 

[[5 8 1]
 [6 0 4]
 [3 2 7]] 

[[6 5 1]
 [8 0 4]
 [3 2 7]] 

[[6 0 1]
 [8 5 4]
 [3 2 7]] 

[[0 6 1]
 [8 5 4]
 [3 2 7]] 

[[6 1 0]
 [8 5 4]
 [3 2 7]] 

[[5 8 1]
 [0 6 4]
 [3 2 7]] 

[[0 8 1]
 [5 6 4]
 [3 2 7]] 

[[5 8 1]
 [6 2 4]
 [3 0 7]] 

[[5 8 1]
 [6 4 0]
 [3 2 7]] 

[[6 5 1]
 [8 2 4]
 [3 0 7]] 

[[6 5 1]
 [8 4 0]
 [3 2 7]] 

[[5 1 4]
 [6 8 0]
 [3 2 7]] 

[[5 1 4]
 [6 0 8]
 [3 2 7]] 

[[5 8 0]
 [6 4 1]
 [3 2 7]] 

[[5 0 8]
 [6 4 1]
 [3 2 7]] 

[[0 5 8]
 [6 4 1]
 [3 2 7]] 

[[5 8 1]
 [3 6 4]
 [0 2 7]] 

[[5 8 1]
 [6 2 4]
 [0 3 7]] 

[[5 8 1]
 [0 2 4]
 [6 3 7]] 

[[0 8 1]
 [5 2 4]
 [6 3 7]] 

[[5 8 1]
 [6 2 4]
 [3 7 0]] 

[[6 5 0]
 [8 4 1]
 [3 2 7]] 

[[6 0 5]
 [8 4 1]
 [3 2 7]] 

[[0 6 5]
 [8 4 1]
 [3 2 7]] 

[[6 5 1]
 [3 8 4]
 [2 0 7]] 

[[6 5 1]
 [3 0 4]
 [2 8 7]] 

[[6 0 1]
 [3 5 4]
 [2 8 7]] 

[[0 6 1]
 [3 5 4]
 [2 8 7]] 

[[6 1 0]
 

[[3 0 1]
 [8 5 4]
 [2 6 7]] 

[[0 3 1]
 [8 5 4]
 [2 6 7]] 

[[3 1 0]
 [8 5 4]
 [2 6 7]] 

[[3 5 8]
 [0 4 1]
 [2 6 7]] 

[[3 6 1]
 [2 5 4]
 [8 0 7]] 

[[3 6 1]
 [2 5 8]
 [0 7 4]] 

[[3 6 1]
 [5 0 4]
 [2 8 7]] 

[[3 0 1]
 [5 6 4]
 [2 8 7]] 

[[0 3 1]
 [5 6 4]
 [2 8 7]] 

[[3 1 0]
 [5 6 4]
 [2 8 7]] 

[[3 6 5]
 [0 8 1]
 [2 7 4]] 

[[3 6 5]
 [2 4 1]
 [0 8 7]] 

[[4 0 5]
 [6 2 1]
 [8 3 7]] 

[[4 0 5]
 [6 8 2]
 [3 7 1]] 

[[4 0 8]
 [5 2 1]
 [6 3 7]] 

[[4 0 8]
 [5 6 1]
 [3 2 7]] 

[[4 5 1]
 [0 8 7]
 [6 3 2]] 

[[4 8 5]
 [6 0 1]
 [3 2 7]] 

[[5 0 1]
 [6 4 7]
 [3 2 8]] 

[[5 0 1]
 [6 7 2]
 [8 3 4]] 

[[5 1 0]
 [3 2 4]
 [6 8 7]] 

[[5 1 0]
 [6 3 8]
 [2 7 4]] 

[[5 1 0]
 [6 4 2]
 [3 8 7]] 

[[5 1 2]
 [0 3 4]
 [6 7 8]] 

[[5 1 2]
 [3 6 4]
 [0 8 7]] 

[[5 1 2]
 [3 8 0]
 [7 6 4]] 

[[5 1 2]
 [3 0 8]
 [7 6 4]] 

[[5 1 2]
 [6 7 8]
 [0 3 4]] 

[[5 1 2]
 [0 7 8]
 [6 3 4]] 

[[0 1 2]
 [5 7 8]
 [6 3 4]] 

[[5 1 2]
 [6 7 8]
 [3 4 0]] 

[[5 1 2]
 [6 7 0]
 [3 4 8]] 

[[5 1 2]
 [8 0 4]
 [6 3 7]] 

[[5 1 4]
 

[[1 6 5]
 [0 2 4]
 [3 7 8]] 

[[6 2 5]
 [1 4 0]
 [3 7 8]] 

[[6 2 0]
 [1 4 5]
 [3 7 8]] 

[[6 5 4]
 [1 8 0]
 [3 2 7]] 

[[6 5 0]
 [1 8 4]
 [3 2 7]] 

[[6 0 5]
 [1 8 4]
 [3 2 7]] 

[[0 6 5]
 [1 8 4]
 [3 2 7]] 

[[1 6 5]
 [0 8 4]
 [3 2 7]] 

[[6 5 4]
 [3 0 8]
 [2 1 7]] 

[[6 0 4]
 [3 5 8]
 [2 1 7]] 

[[0 6 4]
 [3 5 8]
 [2 1 7]] 

[[6 4 0]
 [3 5 8]
 [2 1 7]] 

[[6 5 4]
 [3 1 2]
 [7 0 8]] 

[[6 5 4]
 [3 1 7]
 [8 0 2]] 

[[6 5 4]
 [3 1 8]
 [2 7 0]] 

[[6 5 4]
 [3 1 0]
 [2 7 8]] 

[[6 5 0]
 [3 1 4]
 [2 7 8]] 

[[6 0 5]
 [3 1 4]
 [2 7 8]] 

[[0 6 5]
 [3 1 4]
 [2 7 8]] 

[[6 1 5]
 [3 0 4]
 [2 7 8]] 

[[6 1 5]
 [0 3 4]
 [2 7 8]] 

[[0 1 5]
 [6 3 4]
 [2 7 8]] 

[[6 1 5]
 [3 4 0]
 [2 7 8]] 

[[6 1 0]
 [3 4 5]
 [2 7 8]] 

[[6 0 1]
 [3 4 5]
 [2 7 8]] 

[[6 5 8]
 [0 2 1]
 [4 3 7]] 

[[0 5 8]
 [6 2 1]
 [4 3 7]] 

[[6 5 8]
 [0 3 1]
 [2 4 7]] 

[[0 5 8]
 [6 3 1]
 [2 4 7]] 

[[6 5 8]
 [0 4 7]
 [3 1 2]] 

[[6 5 8]
 [2 1 0]
 [3 7 4]] 

[[6 5 0]
 [2 1 8]
 [3 7 4]] 

[[6 0 5]
 [2 1 8]
 [3 7 4]] 

[[0 6 5]
 

[[1 0 2]
 [8 5 4]
 [6 7 3]] 

[[1 0 2]
 [8 5 7]
 [6 3 4]] 

[[1 0 4]
 [3 2 8]
 [5 6 7]] 

[[0 1 4]
 [3 2 8]
 [5 6 7]] 

[[1 0 4]
 [5 3 8]
 [6 7 2]] 

[[0 1 4]
 [5 3 8]
 [6 7 2]] 

[[1 0 4]
 [6 2 8]
 [3 5 7]] 

[[0 1 4]
 [6 2 8]
 [3 5 7]] 

[[1 0 4]
 [6 3 2]
 [7 8 5]] 

[[1 0 4]
 [6 3 8]
 [2 7 5]] 

[[1 0 4]
 [8 3 2]
 [5 6 7]] 

[[1 0 4]
 [8 5 3]
 [6 7 2]] 

[[1 0 5]
 [6 2 8]
 [3 7 4]] 

[[1 0 6]
 [8 4 5]
 [3 2 7]] 

[[1 0 7]
 [5 6 8]
 [3 4 2]] 

[[1 0 7]
 [8 5 4]
 [6 3 2]] 

[[1 2 0]
 [5 4 6]
 [3 7 8]] 

[[1 2 0]
 [5 8 4]
 [6 3 7]] 

[[1 2 0]
 [6 5 4]
 [8 3 7]] 

[[1 2 0]
 [6 7 5]
 [8 3 4]] 

[[1 2 0]
 [6 8 4]
 [3 5 7]] 

[[1 2 4]
 [0 6 8]
 [3 5 7]] 

[[1 2 4]
 [3 5 0]
 [6 8 7]] 

[[1 2 0]
 [3 5 4]
 [6 8 7]] 

[[1 0 2]
 [3 5 4]
 [6 8 7]] 

[[0 1 2]
 [3 5 4]
 [6 8 7]] 

[[1 2 4]
 [3 6 5]
 [0 7 8]] 

[[1 2 4]
 [3 8 5]
 [0 6 7]] 

[[1 2 4]
 [3 8 5]
 [6 7 0]] 

[[1 2 4]
 [5 8 7]
 [6 3 0]] 

[[1 2 4]
 [6 0 3]
 [8 7 5]] 

[[1 2 4]
 [6 5 3]
 [0 7 8]] 

[[1 2 4]
 [8 6 5]
 [3 0 7]] 

[[1 2 4]
 

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])