In [57]:
from heapq import heappush, heappop
from collections import defaultdict 
from math import inf
import numpy as np 

In [58]:
goal_state = np.array( [                                      
                        [0, 1, 2],                                                                                                                    
                        [3, 4, 5],                                                                                                                    
                        [6, 7, 8],                                                                                                                    
                ])                                                                                                                                    
                                                                                                                                                      
def manhattan_distance(x,y) :                                                                                                                         
    return abs(x[0] - y[0]) + abs(x[1] - y[1])                                                                                                        
                                                                                                                                                      
def adjacents(x, y) :                                                                                                                                 
    for m, n in {(0, 1), (0, -1), (1, 0), (-1, 0)} :                                                                                                  
        x_, y_ = x + m , y + n                                                                                                                        
        if 0 <= x_ <= 2 and 0 <= y_ <= 2 :                                                                                                            
            yield x_, y_                                                                                                                              
                                                                                                                                                      
def estimated_cost(a) :                                                                                                                               
    sum_ = 0                                                                                                                                          
    for i in range(8) :                                                                                                                               
        x, y = np.where(a.value == i)                                                                                                                 
        x_, y_ = np.where(goal_state == i)                                                                                                            
        sum_ += manhattan_distance((x,y) , (x_,y_))                                                                                                   
    return sum_                                                                                                                                       
                  
class State : 
    def __init__(self, array) :
        self.value = array 
        self.parent = None
            
    def __hash__(self) : 
        return hash(str(self.value))
    
    def __eq__(self, other) : 
        return isinstance(other, State)
    
    def __lt__(self, other) : 
        return True 
    
    def set_parent(self, p) : 
        self.parent = p
        
    def next_states(self) : 
        s = self.value
        x, y = np.where(s == 0) 
        x, y = x[0], y[0] 
        for x_, y_ in adjacents(x,y) : 
            next_s = np.copy(s)
            next_s[x][y] = next_s[x_][y_] 
            next_s[x_][y_] = 0 
            yield State(next_s)
            
    def print_path(self) : 
        if self.parent == None : 
            return 
        self.parent.print_path()
        print(self.value, "\n")
        
    @staticmethod 
    def random_state() : 
        x = np.arange(9) 
        np.random.shuffle(x)
        return State(x.reshape(3,3))
    

In [59]:
def is_goal_state(x) : 
    return np.all(x.value == goal_state)

def search(s) : 
    heap = [(0, s)] 
    g = defaultdict(lambda : float('inf'))
    g[s] = 0 
    visited = set()
    while heap : 
        _, v = heappop(heap) 
        if is_goal_state(v): 
            return v
        for next_ in v.next_states() : 
            if next_ not in visited and \
                g[v] + 1 < g[next_] :   
                g[next_] = g[v] + 1 
                next_.set_parent(v)
                heappush(heap, (g[next_] + \
                                estimated_cost(next_),\
                                next_))
            
        visited |= {v}

In [60]:
x = State.random_state() 
print(x.value)
y = search(x)

[[5 2 8]
 [7 3 4]
 [0 1 6]]


In [61]:
y.print_path()

[[5 2 8]
 [0 3 4]
 [7 1 6]] 

[[5 2 8]
 [3 0 4]
 [7 1 6]] 

[[5 2 8]
 [3 1 4]
 [7 0 6]] 

[[5 2 8]
 [3 1 4]
 [7 6 0]] 

[[5 2 8]
 [3 1 0]
 [7 6 4]] 

[[5 2 0]
 [3 1 8]
 [7 6 4]] 

[[5 0 2]
 [3 1 8]
 [7 6 4]] 

[[5 1 2]
 [3 0 8]
 [7 6 4]] 

[[5 1 2]
 [3 6 8]
 [7 0 4]] 

[[5 1 2]
 [3 6 8]
 [7 4 0]] 

[[5 1 2]
 [3 6 0]
 [7 4 8]] 

[[5 1 0]
 [3 6 2]
 [7 4 8]] 

[[5 0 1]
 [3 6 2]
 [7 4 8]] 

[[0 5 1]
 [3 6 2]
 [7 4 8]] 

[[3 5 1]
 [0 6 2]
 [7 4 8]] 

[[3 5 1]
 [6 0 2]
 [7 4 8]] 

[[3 0 1]
 [6 5 2]
 [7 4 8]] 

[[3 1 0]
 [6 5 2]
 [7 4 8]] 

[[3 1 2]
 [6 5 0]
 [7 4 8]] 

[[3 1 2]
 [6 0 5]
 [7 4 8]] 

[[3 1 2]
 [6 4 5]
 [7 0 8]] 

[[3 1 2]
 [6 4 5]
 [0 7 8]] 

[[3 1 2]
 [0 4 5]
 [6 7 8]] 

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

