In [144]:
import numpy as np 

In [145]:
class State : 
    def __init__(self, board=None) : 
        if board is not None : 
            self.board = board 
        else : 
            self.board = np.zeros((3,3))

    def next_actions(self) : 
        for x in range(3) : 
            for y in range(3) :
                if self.board[x][y] == 0 : 
                    yield x, y 

    def next_state(self, x, y, player) : 
        board = self.board.copy() 
        board[x][y] = player  
        return State(board)
    
    def move(self, x, y, player) : 
        self.board[x][y] = player 
    
    def is_terminal(self) :  
        def is_draw() :  
            if not np.any(self.board == 0) : 
                return True 
            return False 

        def is_valid(line) : 
            if len(np.unique(line)) == 1\
            and line[0] != 0 : 
                return True
            return False

        def check_diagonal() : 
            if is_valid(np.diag(self.board)) \
            or is_valid(np.diag(np.fliplr(self.board))) : 
                return True 
            else : 
                return False 

        def check_row_col() : 
            for i in range(3) : 
                if is_valid(self.board[:,i]) : 
                    return True, self.board[0,i] 
                if is_valid(self.board[i,:]) : 
                    return True, self.board[i][0] 
                return False, None 

        if is_draw() : 
            return 0  
        if check_diagonal() : 
            return self.board[1][1] 
        ok, v = check_row_col()
        if ok : 
            return v 
        return -2 

    

In [148]:
from math import inf
def minimax(state, player) : 
    if player == 1 : 
        _, move = max_(state) 
    else : 
        _, move = min_(state)
    return move
    
def max_(state) : 
    
    v = state.is_terminal() 
    if v != -2 :
        return v, None 
    v, move = -inf, None
     
    for action in state.next_actions() : 
        v_, _ = min_(state.move(*action, 1))
        if v_ > v : 
            v, move = v_, action 
    return v, move

def min_(state) : 
    v = state.is_terminal() 
    if v != -2 : 
        return v, None 
    v, move = inf, None
    for action in state.next_actions() : 
        v_, _ = max_(state.move(*action, -1))
        if v_ < v : 
            v, move = v_, action 
    return v, move 

In [139]:
m = State(np.array([[1, 1, -1], [-1, -1, 0], [1, 0, 0]]))
minimax(m, 1)

(1, 2)

In [149]:
game = State() 
while True : 
    if game.is_terminal() != -2 : 
        break 
    print(game.board) 
    print("choose your move: ") 
    x, y = map(int ,input().split(','))
    game.board[x][y] = 1
    x_, y_ = minimax(game, -1) 
    print(f"computer chose {x_} {y_}")
    game.board[x_][y_] = -1 


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
choose your move: 
0,0


AttributeError: 'NoneType' object has no attribute 'is_terminal'

In [143]:
x = [1 , 2 ,3] 
y = x 
y[0] = 5 
x, y

([5, 2, 3], [5, 2, 3])